//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinitionMultiLanguage
    {
        public long Pid { get; set; }
        public string Name { get; set; }
        public string vi_VN { get; set; }
        public string ar_AE { get; set; }
        public string sq_AL { get; set; }
        public string uz_Latn_UZ { get; set; }
        public string en_US { get; set; }
        public string hy_AM { get; set; }
        public string az_Cyrl_AZ { get; set; }
        public string pl_PL { get; set; }
        public string fa_IR { get; set; }
        public string et_EE { get; set; }
        public string eu_ES { get; set; }
        public string be_BY { get; set; }
        public string ka_GE { get; set; }
        public string bs_Latn_BA { get; set; }
        public string pt_BR { get; set; }
        public string bg_BG { get; set; }
        public string ca_ES { get; set; }
        public string he_IL { get; set; }
        public string da_DK { get; set; }
        public string de_DE { get; set; }
        public string nl_NL { get; set; }
        public string ko_KR { get; set; }
        public string el_GR { get; set; }
        public string hi_IN { get; set; }
        public string te_IN { get; set; }
        public string ms_MY { get; set; }
        public string mn_MN { get; set; }
        public string es_ES { get; set; }
        public string nb_NO { get; set; }
        public string ur_PK { get; set; }
        public string ru_RU { get; set; }
        public string ja_JP { get; set; }
        public string fr_FR { get; set; }
        public string fi_FI { get; set; }
        public string cs_CZ { get; set; }
        public string th_TH { get; set; }
        public string tr_TR { get; set; }
        public string sv_SE { get; set; }
        public string zh_CN { get; set; }
        public string it_IT { get; set; }
        public string id_ID { get; set; }
        public string sr_Latn_BA { get; set; }
        public string kn_IN { get; set; }
        public string en_IE { get; set; }
        public string zu_ZA { get; set; }
        public string ro_RO { get; set; }
        public string mi_NZ { get; set; }
        public string mr_IN { get; set; }
        public string uk_UA { get; set; }
        public string sr_Latn_CS { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
