//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDetail
    {
        public long Group { get; set; }
        public long Code { get; set; }
        public string Value { get; set; }
        public Nullable<int> Active { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Int1 { get; set; }
        public Nullable<decimal> Int2 { get; set; }
        public Nullable<decimal> Dec1 { get; set; }
        public Nullable<decimal> Dec2 { get; set; }
        public string Varchar1 { get; set; }
        public string Varchar2 { get; set; }
        public Nullable<System.DateTime> Datetime1 { get; set; }
        public Nullable<System.DateTime> Datetime2 { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
