//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<long> ProductDettailId { get; set; }
        public string SizeValue { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string ColorValue { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UnitCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
