//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Pid { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Image { get; set; }
        public string URL { get; set; }
        public string MetaTitle { get; set; }
        public string SeoTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Size { get; set; }
        public Nullable<long> TypeCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> Promotion { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> DistributorId { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<long> Producer { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string Video { get; set; }
    }
}
