//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<long> ProvinceID { get; set; }
        public Nullable<long> DistrictID { get; set; }
        public Nullable<long> WardID { get; set; }
        public string Address { get; set; }
        public Nullable<int> AddressType { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
