//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trucking
    {
        public long Id { get; set; }
        public string TruckingCode { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
    }
}
